### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ShrewHools** [ShrewHools/react-tic-tac-toe#1]
- [ ] 1. Отобразите позицию для каждого хода в формате (колонка, строка) в списке истории ходов.
- [ ] 2. Выделите выбранный элемент в списке ходов.
- [ ] 3. Перепишите Board, используя вложенные циклы для создания клеток, вместо их жёсткого кодирования.
- [ ] 4. Добавьте переключатель, который позволит вам сортировать ходы по возрастанию или по убыванию.
- [ ] 5. Когда кто-то выигрывает, подсветите три клетки, которые привели к победе.
- [ ] 6. Когда победителя нет, покажите сообщение о том, что игра окончилась вничью.
- [ ] 7. Разбить на компоненты
